name: Check

on:
  push:
    branches: [main]
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  flake-check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - name: Check devShell evaluates
        run: nix eval .#devShells.aarch64-darwin.default --json > /dev/null

      - name: Check formatting
        run: nix develop --command pre-commit run --all-files
